#!/usr/bin/env ruby

require 'autotest/timestamp'

module Autotest::GnomeNotify
  def self.notify title, msg, img
    system "notify-send '#{title}' '#{msg}' -i #{img} -t 3000"
  end

  Autotest.add_hook :ran_command do |at|
    image_root = "/usr/share/icons/Tango/96x96/emotes"
    results = [at.results].flatten.join "\n"
    results.gsub!(/\\e\[\d+m/, '')
    output = results.slice(/(\d+)\sexamples?,\s(\d+)\sfailures?/)
    puts output.inspect
    if output
      if $~[2].to_i > 0
        notify "FAIL", "#{output}", "#{image_root}/face-surprise.png"
      else
        notify "Pass", "#{output}", "#{image_root}/face-smile.png"
      end
    end
  end

end
